#!/usr/bin/env node
/**
 * localstack-env.mjs
 * ------------------
 * Writes `.env.localstack.local` with the publishable key of the running local
 * Supabase stack, so `npm run dev:test` can point the app at it.
 *
 * Why generate rather than commit the key: the local anon key is a JWT signed
 * with the CLI's development secret. It is not a secret, but it is long, it
 * changes if the stack's secret is ever customised, and a wrong one fails with
 * an authentication error that says nothing about where it came from. Asking
 * the CLI is exact.
 *
 * The URL and the login address are committed in `.env.localstack`; only the
 * key lives here, in a `.local` file git already ignores.
 *
 * Usage:
 *   node scripts/localstack-env.mjs
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const OUTPUT = resolve(process.cwd(), '.env.localstack.local');

let raw;
try {
  raw = execFileSync('supabase', ['status', '-o', 'env'], {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  });
} catch {
  console.error(
    'Could not read the local Supabase stack.\n' +
    'Start it first:\n\n' +
    '  supabase start\n' +
    '  supabase db reset   # applies migrations, then supabase/seed.sql\n',
  );
  process.exit(1);
}

// `supabase status -o env` emits KEY="value" lines.
const values = new Map(
  raw
    .split('\n')
    .map(line => line.match(/^([A-Z_]+)="?(.*?)"?$/))
    .filter(Boolean)
    .map(match => [match[1], match[2]]),
);

const anonKey = values.get('ANON_KEY');
if (!anonKey) {
  console.error('The stack is running but reported no ANON_KEY. Try `supabase stop` then `supabase start`.');
  process.exit(1);
}

writeFileSync(
  OUTPUT,
  '# Generated by scripts/localstack-env.mjs. Do not edit; do not commit.\n' +
  `VITE_SUPABASE_PUBLISHABLE_KEY=${anonKey}\n`,
);

console.log(`Wrote ${OUTPUT}`);
