// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { withRestTimeout } from './rest-timeout-fetch';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Consumers import the `supabase` export below via the `@/` alias.

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Database API requests fail after a hard limit instead of hanging on a
  // dead connection (rest-timeout-fetch.ts).
  global: { fetch: withRestTimeout((input, init) => fetch(input, init), SUPABASE_URL) },
});
